resolver: lts-18.28
packages:
 - .

#
# there was actually no immediate reason to depend on the latest versions of
# these libraries other than to show the way you add specific versions to your
# Stack resolver if you need something newer than what is in the snaphot above.
#

extra-deps:
  - core-data-0.3.2.2
  - core-program-0.4.6.4
  - core-telemetry-0.2.2.0
  - core-text-0.3.7.1
